pestina/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve
from products import views

urlpatterns = [
    path('',include('products.urls')),
    path('blog/',include('products.blogurls')),
    path('admin_jan_ammat_ino_be_kasi_nade/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

handler404 = 'products.views.custom_404'
handler500 = lambda request: views.unknown_error(request, status_code=500)
handler403 = lambda request, exception: views.unknown_error(request, exception, status_code=403)
handler400 = lambda request, exception: views.unknown_error(request, exception, status_code=400)
handler405 = lambda request, exception: views.unknown_error(request, exception, status_code=405)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path , include
from . import views
from django.contrib import admin

urlpatterns = [
    path('',views.homepage,name='home'),

    path('login/',views.login_page,name='login'),
    path('login/forgot_password',views.forgotpass,name='forgot-password'),

    path('sign_up/',views.signup,name='sign-up'),
    path('sign_up/verify_number',views.number_verify,name='verify-numver'),
    path('sign_up/set_password',views.set_password,name='set_password'),

    path('logout',views.user_logout,name='logout'),

    path('send_ticket/<str:ticket_type>/',views.send_ticket,name='send-ticket'),
    path('ticket_sent/',views.registered_ticket,name='registered-ticket'),
    path('buy-product/<int:pid>/',views.buy_product1,name='buy-product'),
    path('confirm_buy/',views.buy_product2,name='confirm'),
    path('order_sent/',views.registered_order,name='resgtered-order'),

    path('products/',views.view_products,name='products'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('about-us/',views.about_us,name='about-us'),
]

products/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    first_name = models.CharField(max_length=20,verbose_name='نام کاربر')
    last_name = models.CharField(max_length=20,verbose_name='نام خانوادگی کاربر')
    phone_number = models.CharField(max_length=15,unique=True,verbose_name='شماره تلفن کاربر')
    is_verified = models.BooleanField(default=False,verbose_name='وضعیت تایید شدن شماره تلغن')
    ip_address = models.GenericIPAddressField(null=True,blank=True,verbose_name='آیپی کاربر هنگام ثبت نام')
    register_time = models.DateTimeField(auto_now=True,verbose_name='زمان ثبت نام')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Product(models.Model):

    class ptype(models.TextChoices):
        AKBARI = "akbari","اکبری"
        FANDOGHI = "fandoghi","فندوقی"
        AHMADAGHAII = "ahmadaghaii","احمد آقایی"
        KALE_GHOOCHI = 'kaleghoochi','کله قوچی'
        SHAHPASAND = 'shahpasand','شاه پسند'
        SEPID = 'sefid','سفید'
        BADAMI = 'badami','بادامی'
        KHANJARI = 'khanjari','خنجری'
        MAKHLOOT = 'makhloot',' مخلوط'
        
    class pstatus(models.TextChoices):
        KHANDAN = 'khandan','خندان'
        DAHANBAST = 'dahanbast','دهن بست'
        ABKHANDAN = 'abkhandan','آب خندان'
        TARKIBI = 'tarkibi','ترکیبی'

    class pquality(models.TextChoices):
        D1 = 'd1','درجه یک'
        D2 = 'd2','درجه دو'
        D3 = 'd3','درجه سه'
        D4 = 'd4','درجه چهار'

    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='کاربر')
    id = models.AutoField(primary_key=True,verbose_name='آیدی محصول')

    photo = models.ImageField(verbose_name='عکس محصول',upload_to='prdphotos')
    kind = models.CharField(max_length=20,choices=ptype.choices,verbose_name='نوع پسته')
    status = models.CharField(max_length=20,choices=pstatus.choices,verbose_name='وضعیت محصول')
    ounce = models.PositiveIntegerField(verbose_name='انس محصول')
    quality = models.CharField(max_length=20,choices=pquality.choices,verbose_name='(کیفی) کیفیت محصول')
    price = models.DecimalField(max_digits=13,decimal_places=0,verbose_name='(تومان) قیمت محصول')
    show_inventory = models.BooleanField(default=True,verbose_name='وضعیت نمایش وزن محصول')
    inventory = models.FloatField(verbose_name='وزن محصول')
    min_order = models.FloatField(null=True,blank=True,verbose_name='حداقل سفارش (کیلوگرم - خالی برای بدون محدودیت)')
    max_order = models.FloatField(null=True,blank=True,verbose_name='حداکثر سفارش (کیلوگرم - خالی برای بدون محدودیت)')
    discription = models.CharField(max_length=500,null=True,blank=True,verbose_name='توضیحات بیشتر برای محصول')
    free_shipping = models.BooleanField(default=False,verbose_name='ارسال رایگان')
    shipping_cost = models.DecimalField(max_digits=13,null=True,blank=True,decimal_places=0,verbose_name='(تومان) هزینه ارسال')
    is_pestina_product = models.BooleanField(default=False,verbose_name='محصول پستینا')
    is_confirmed = models.BooleanField(default=False,verbose_name='وضعیت تایید شدن توسط ادمین')
    ip_address = models.GenericIPAddressField(null=True,blank=True,verbose_name='آیپی')
    upload_time = models.DateTimeField(auto_now_add=True,verbose_name='تاریخ ثبت محصول')

    def save(self,*args,**kwargs):
        if self.free_shipping :
            self.shipping_cost = None
        super().save(*args,**kwargs)


    def __str__(self):
        return f"{self.kind} uploaded by {'admin' if self.is_pestina_product else self.user.first_name}"


# class RawData(models.Model):
#     user_logout_time = models.BigIntegerField(verbose_name='مدت زمان لاگین ماندن کاربر (به ثانیه)',default=2*60*60)
#     product_per_page = models.IntegerField(verbose_name='تعداد محصول قابل نمایش در هر صفحه',default=9)

#     minimum_gain_order = models.FloatField(verbose_name='کمترین مقدار قابل سفارش از هز محصولی (به کیلوگرم)',default=0.1)

#     max_post_gain = models.FloatField('بیشترین وزن قابل ارسال با پست (به کیلوگرم)',default=30)
#     max_post_cost = models.DecimalField(max_digits=13,decimal_places=0,verbose_name='بیشترین هزینه ارسال پست (به تومان)',)

#     max_tipax_gain = models.FloatField(verbose_name='بیشترین وزن قابل ارسال با تیپاکس (به کیلوگرم)')
#     max_tipax_cost = models.DecimalField(max_digits=13,decimal_places=0,verbose_name='بیشترین هزینه ارسال تیپاکس (به تومان)')

    

class Ticket(models.Model):
    class TicketType(models.TextChoices):
        FEEDBACK = "feedback","نظرات و پیشنهادات"
        PURCHASE = "purchase","درخواست خرید محصول"
        TECHNICAL = "technical","نقص فنی سایت"

    user = models.ForeignKey(User,null=True,blank=True,on_delete=models.CASCADE,verbose_name='کاربر')

    ticket_id = models.AutoField(primary_key=True,verbose_name='شماره تیکت')
    buyer_namelastname = models.CharField(max_length=30,verbose_name='نام خریدار') #need to fill
    buyer_phone = models.CharField(max_length=20,verbose_name='شماره تلفن')
    ticket_type = models.CharField(max_length=20,choices=TicketType.choices,verbose_name='نوع تیکت')
    request_title = models.CharField(max_length=20,verbose_name='عنوان تیکت')
    request_discription = models.CharField(max_length=150,verbose_name='متن درخواست')
    ticket_time = models.DateTimeField(auto_now_add=True,verbose_name='تاریخ ثبت تیکت')
    ip_address = models.GenericIPAddressField(null=True,blank=True,verbose_name='أیپی')

    def __str__(self):
        return f"{self.ticket_type} -> by {self.buyer_namelastname} {self.buyer_phone}"

class BuyTicket(models.Model):
    id = models.AutoField(primary_key=True,verbose_name='شماره سفارش')
    name = models.CharField(max_length=30,verbose_name='نام خریدار')
    phone = models.CharField(max_length=20,verbose_name='شماره تلفن')
    product = models.ForeignKey(Product,on_delete=models.PROTECT,verbose_name='محصول سفارش داده شده')
    gain = models.FloatField(verbose_name='مقدار (به کیلو)')
    price = models.FloatField(verbose_name='قیمت نهایی')
    post_code = models.BigIntegerField(verbose_name='کد پستی')
    address = models.CharField(max_length=1500,verbose_name='آدرس')
    buy_time = models.DateTimeField(auto_now=True,verbose_name='تاریخ سفارش')
    ip_address = models.GenericIPAddressField(null=True,blank=True,verbose_name='آیپی')

    def __str__(self):
        return self.buyer_namelastname

products/forms.py
from django import forms
# from .models import
# from .models import tickets
from .models import User
from django.core.exceptions import ValidationError
from products.templatetags.custom_filters import format_weight
#---------------------------------------------------

#  ------ ticket forms {  
class OrderForm(forms.Form):
    buyer_namelastname = forms.CharField(max_length=30, required=True, label='نام و نام خانوادگی')
    buyer_phonenumber = forms.CharField(max_length=15, required=True, label='شماره تلفن')
    request_title = forms.CharField(max_length=20, required=True, label='عنوان')
    request_text = forms.CharField(max_length=200, required=True, label='متن درخواست')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(OrderForm, self).__init__(*args, **kwargs)

    def clean_buyer_namelastname(self):
        name = self.cleaned_data['buyer_namelastname']
        if len(name) >= 29:
            raise ValidationError('بیش از حد مجاز است')
        elif len(name) < 5:
            raise ValidationError('بسیار کوتاه است')
        return name

    def clean_buyer_phonenumber(self):
        phone = self.cleaned_data['buyer_phonenumber']
        if not phone.isdigit():
            raise ValidationError('شماره تلفن باید فقط شامل اعداد باشد')
        if len(phone) != 11:
            raise ValidationError('شماره تلفن باید ۱۱ رقم باشد')
        return phone

    def clean_request_title(self):
        title = self.cleaned_data['request_title']
        if len(title) > 19:
            raise ValidationError('بیش از حد مجاز است')
        elif len(title) < 5:
            raise ValidationError('بسیار کوتاه است')
        return title

    def clean_request_text(self):
        text = self.cleaned_data['request_text']
        if len(text) >= 198:
            raise ValidationError('بیش از حد مجاز است')
        elif len(text) < 5:
            raise ValidationError('بسیار کوتاه است')
        return text

    def clean(self):
        cleaned_data = super().clean()
        phone = cleaned_data.get("buyer_phonenumber")

        if phone and self.request and not self.request.user.is_authenticated:
            if User.objects.filter(phone_number=phone).exists():
                raise ValidationError("این شماره تلفن قبلاً در سایت ثبت شده است. لطفاً ابتدا وارد شوید.")
        
        return cleaned_data
#  ------ ticket forms }  
        

#  ------ order forms {  
class BuyForm(forms.Form):
    buyer_namelastname = forms.CharField(max_length=30,required=True,label='نام و نام خانوادگی') #need to fill
    buyer_phone = forms.CharField(max_length=15,required=True,label='شماره تلفن')
    gain_product = forms.FloatField(required=True,label='مقدار (به کیلو)')
    order_discription = forms.CharField(required=False,max_length=400,label='توضیحات سفارش')

    def clean_buyer_namelastname(self):
        name = self.cleaned_data['buyer_namelastname']
        if len(name) >= 29:
            raise forms.ValidationError('بیش از حد مجاز است')
        elif len(name) < 5 :
            raise forms.ValidationError('بسیار کوتاه است')
        return name
    
    def clean_buyer_phone(self):
        phone = self.cleaned_data['buyer_phone']
        if len(str(phone)) < 10 :
            raise forms.ValidationError('بسیار کوتاه است')
        return phone

    def clean_gain_product(self):
        gain = self.cleaned_data['gain_product']
        if float(gain) < 0.5 :
            raise forms.ValidationError('نمیتواند کمتر از 500 گرم باشد')
        elif float(gain) > 10 :
            raise forms.ValidationError('در حال حاضر امکان ثبت سفارش بیش از 10 کیلوگرم وجود ندارد')
        
        return gain

    def clean_order_discription(self):
        text = self.cleaned_data['order_discription']
        if len(text) >= 390 :
            raise forms.ValidationError('بیش از حد مجاز است')

        return text

class CheckGainBuyForm(forms.Form):
    quantity = forms.DecimalField(label='مقدار سفارش (کیلوگرم)',min_value=0.1)
    def __init__(self, *args, min=None, max=None, **kwargs):
        super().__init__(*args,**kwargs)
        self.min = min
        self.max = max
    def clean_quantity(self):
        gain = self.cleaned_data.get('quantity')
        if self.min is not None and gain < self.min :
            raise forms.ValidationError(f'حداقل سفارش {format_weight(self.min)} است')
        if self.max is not None and gain > self.max:
            raise forms.ValidationError(f'حداکثر سفارش {format_weight(self.max)} است')
        return gain
    
class CheckPersonalBuyForm(forms.Form):
    buyer_namelastname = forms.CharField(max_length=30,required=True,label='نام و نام خانوادگی')
    buyer_phone = forms.CharField(max_length=15,required=True,label='شماره تلفن')
    post_code = forms.CharField(max_length=12,required=True,label='کد پستی')
    address = forms.CharField(max_length=1499,required=True,label='آدرس') #need to fill

    def clean_buyer_namelastname(self):
        name = self.cleaned_data['buyer_namelastname']
        if len(name) >= 29:
            raise forms.ValidationError('بیش از حد مجاز است')
        elif len(name) < 5 :
            raise forms.ValidationError('بسیار کوتاه است')
        return name
    
    
    def clean_buyer_phone(self):
        phone = self.cleaned_data['buyer_phone']
        if not phone.isdigit():
            raise ValidationError('شماره تلفن باید فقط شامل اعداد باشد')
        if not len(phone) == 11 :
            raise ValidationError('شماره تلفن نامعتبر است باید 11 رقم باشد')
        
        return phone
    def clean_post_code(self):
        code = self.cleaned_data['post_code']
        if not len(code) == 10 :
            raise ValidationError('باید 10 رقم باشد معتبر نیست')
        return code
        
    def clean_address(self):
        address = self.cleaned_data['address']
        if len(address) < 25 :
            raise ValidationError('وارد شده کوتاه است لطفا اطلاعات ارسال را کامل تر بنویسید')
        if len(address) > 1498 : 
            raise ValidationError('آدرس بیش از حد مجاز است لطفا خلاصه تر بنویسید')
        return address

#  ------ order forms }  



#  ------ login forms {  
class LoginForm(forms.Form):
    phone_number = forms.CharField(max_length=50)
    password = forms.CharField(max_length=120)

class SignUpForm(forms.ModelForm):
    first_name = forms.CharField(max_length=18,required=True,label='first_name')
    last_name = forms.CharField(max_length=18,required=True,label='last_name')
    phone_number = forms.CharField(max_length=13,required=True,label='phone_number')

    class Meta:
        model = User
        fields = ['first_name','last_name','phone_number']
    
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if len(first_name) <= 2 :
            raise ValidationError('نام بسیار کوتاه است')
        elif len(first_name) >= 17 :
            raise ValidationError('نام بسیار طولانی است')
        
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if len(last_name) <= 2 :
            raise ValidationError('نام خانوادگی بسیار کوتاه است')
        elif len(last_name) >= 17 :
            raise ValidationError('نام خانوادگی بسیار طولانی است')
        
        return last_name
    
    def clean_phone_number(self):
        phone = (self.cleaned_data['phone_number']).strip()
        if not phone.isdigit():
            raise ValidationError('شماره تلفن باید فقط شامل اعداد باشد')
        if not len(phone) == 11 :
            raise ValidationError('شماره تلفن نامعتبر است')
        if User.objects.filter(phone_number=phone).exists() :
            raise ValidationError('این شماره تلفن قبلا ثبت شده است')
        
        return phone
                
class VerifyNumberForm(forms.Form):

    code = forms.CharField(max_length=5,required=True,label='verification')

    def clean_code(self):
        code = (self.cleaned_data['code']).strip()

        if not code.isdigit() :
            raise ValidationError('کد تایید باید عددی باشد')
        if not len(code) == 5 :
            raise ValidationError('کد باید به طول ۵ کاراکتر باشد')
        
        return code
    
class SetPasswordForm(forms.Form):
    new_password1 = forms.CharField(max_length=128,required=True,label='password')
    new_password2 = forms.CharField(max_length=128,required=True,label='repassword')

    def clean_new_password1(self):
        password = self.cleaned_data.get('new_password1')
        if len(password) < 8 :
            raise ValidationError('پسورد نمیتواند کمتر از ۸ کاراکتر باشد')
        
        if not any(char.isdigit() for char in password) :
            raise ValidationError('رمز عبور باید حداقل یک کاراکتر عددی داشته باشد')
        
        if not any(char.isalpha() for char in password) :
            raise ValidationError('پسورد باید شامل حروف انگلیسی کوچک و بزرگ باشد')
        
        return password
    
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('new_password1')
        password2 = cleaned_data.get('new_password2')
        if password1 and password2 and password1 != password2 :
            self.add_error('new_password2','رمز عبور و تکرار آن باید یکسان باشند')
 
        return cleaned_data
#  ------ login forms }  







    

products/templates/buy_product.html
{% extends 'patterns/base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}پستینا | خرید پسته {{p.get_kind_display}} {{p.get_status_display}} {{p.get_quality_display}}{% endblock title %}
{% block typebody %}<body class="topics-listing-page" dir="rtl" id="top" style="text-align: right;">{% endblock %}
    {% block navitem %}
    <ul class="navbar-nav ms-lg-5 me-lg-auto">
        <li class="nav-item">
            <a class="nav-link click-scroll" href="{% url 'products' %}">
                <strong><span style="font-size:var(--menu-font-size);">
                    <i class="fa-solid fa-duotone fa-shopping-cart"></i>
                </span>لیست محصولات</strong>
            </a>
        </li>
        <li class="nav-item">            
            <a class="nav-link click-scroll" href="{% url 'home' %}">
                <strong><span style="font-size:var(--menu-font-size);">
                    <i class="fa-solid fa-duotone fa-home"></i>
                </span>خانه</strong>
            </a>
        </li>
        <li class="nav-item">            
            <a class="nav-link click-scroll" href="{% url 'blog' %}">
                <strong><span style="font-size:var(--menu-font-size);">
                    <i class="fa-solid fa-duotone fa-coffee"></i>
                </span>وبلاگ پستینا</strong>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link click-scroll" href="{% url 'send-ticket' 'technical' %}">
                <strong><span style="font-size:var(--menu-font-size);">
                    <i class="fa-solid fa-duotone fa-phone"></i>
                </span>ارتباط با پشتیبانی</strong>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link click-scroll" href="{% url 'about-us' %}">
                <strong><span style="font-size:var(--menu-font-size);">
                    <i class="fa-solid fa-duotone fa-info-circle"></i>
                </span>درباره ما</strong>
            </a>
        </li>
    </ul>
    {% endblock navitem %}
{% block header %}
<header class="site-header d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-7 col-12">
                <h2 class="text-white">محصولات / پسته {{p.get_kind_display}} {{p.get_status_display}} {{p.get_quality_display}}</h2>
            </div>
        </div>
    </div>
</header>
{% endblock header %}
{% block content %}
       <section class="section-padding section-bg">
            <div class="container" style="text-align: center;">
                <div class="row" style="flex-direction: column;align-items: center;">
                    <div class="col-lg-12 col-12">
                        <h3 class="mb-4 pb-2">لطفا مقدار محصول جهت سفارش را وارد کنید</h3>
                    </div>

                    <div class="col-lg-6 col-12 mx-auto mt-5 mt-lg-0" style="text-align: center;">
                        <img class="google-map" src="{{ p.photo.url }}" alt="" width="100%" height="250" style="border:0;" loading="lazy" />
                        <h5 class="mt-4 mb-2">مشخصات محصول جهت سفارش</h5>
                        <div class="product-box">
                            <div class="product-left">
                                <p><b>پسته {{p.get_kind_display}}</b></p>
                                <ul>
                                    <li>وضعیت پسته : {{ p.get_status_display }}</li>
                                    <li>انس پسته : {{ p.ounce }}</li>
                                    <li>کیفیت محصول : {{ p.get_quality_display }}</li>
        
                                    {% if p.show_inventory %}
                                    <li>مقدار موجود : {{ p.inventory | format_weight}}</li>
                                    {% endif %}
                                    {% if p.discription %}
                                    <li>توضیحات محصول : {{p.discription}}</li>
                                    {% endif %}        

                                </ul>
                            </div>

                            <div class="product-right">
                                <p><b>توضیحات سفارش محصول</b></p>
                                <ul>

                                    {% if p.min_order %}
                                    <li>کف سفارش : {{p.min_order | format_weight}}</li>
                                    {% endif %}
        
                                    {% if p.max_order %}
                                    <li>سقف سفارش : {{p.max_order | format_weight}}</li>
                                    {% endif %}    

                                    {% if p.free_shipping and p.is_pestina_product %}
                                    <li>
                                        محصول متعلق به پستینا و دارای ارسال رایگان است
                                    </li>
                                    {% elif p.is_pestina_product %}
                                    <li>
                                    محصول متعلق به پستینا است لازم به ذکر است محصولات پستینا تایید شده و دارای کیفیت بهتری هستند
                                    </li>
                                    {% elif p.free_shipping %}
                                     <li>
                                         محصول دارای ارسال رایگان است
                                    </li>
                                    {% endif %} 
                                </ul>
                            </div>
                            
                        </div>
                    </div>

                    <div class="col-lg-6 col-12">
                        <form class="custom-form contact-form" method="post" action="{% url 'buy-product' pid=p.id %}" role="form">
                            {% csrf_token %}
                            <div class="row" style="justify-content:center;">
                                <div class="col-lg-12 col-12">
                                    <div class="form-floating">
                                        <input type="number" id="weightInput" min="0" step="0.2" name="quantity" class="form-control" placeholder="gain" required
                                            {% if form.gain_product.value %} value="{{ form.gain_product.value }}" {% endif %} />
                                        <label for="weightInput">وزن محصول (برحسب کیلوگرم)</label>
                                    </div>
                                </div>

                                {% if form.errors %}
                                    {% for field in form %}
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                            <blockquote style="text-align:center;margin: 0px 16px 11px 0;padding: 0px;font-size: 16px;color:var(--primary-color);width: 95%;">{{error}}</blockquote>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}

                                <div class="col-lg-4 col-12 ms-auto1">
                                    <button type="submit" class="form-control">مرحله بعد</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </section>
    </main>
{% endblock %}

products/templates/error_page.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <link rel="icon" href="{% static 'images/fav.svg' %}" sizes="76*76" type="image/svg+xml">
        <link href="{% static 'css/error-page.css' %}" rel="stylesheet"/>

        <link href="{% static 'awesome-css/duotone.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'awesome-css/fontawesome.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'awesome-css/brands.css' %}" rel="stylesheet"/>
        <link id="themeStylesheet" rel="stylesheet" href="{% static 'css/root/light-root.css' %}" rel="stylesheet"/>
        <script src="{% static 'js/theme-toggle.js' %}" defer></script>
  <title>
    {% if type == '404' %}
    صفحه مورد نظر یافت نشد - 404
    {% else %}
    خطای {{status_code}}
    {% endif %}
</title>
</head>
<body>
  <div class="gradient"></div>
  <div class="container">
    {% if type == '404' %}
    <h1 style="font-size: var(--h4-font-size);">خطای404 <i class="fa-duotone fa-solid fa-face-sad-sweat"></i><br/> صفحه مورد نظر پیدانشد </h1>
    <p>بنظر میرسه صفحه ای که دنبالشی گم شده یا وجود نداره این پایین بهت کمک میکنیم برگردی به همون جایی که ازش اومدی <i class="fa-duotone fa-solid fa-face-smile-upside-down"></i></p>
    {% else %}
    <h1 style="font-size: var(--h4-font-size);">خطای {{error}} <i class="fa-duotone fa-solid fa-cloud-exclamation"></i><br/>متاسفانه خطایی رخ داده است</h1>
    <p>بابت خطایی که رخ داده پوزش میطلبیم شما میتوانید نوع خطا و طریقه ای که با این خطا برخورد کردید را به پشتیبانی اطلاع دهید </p>
    {% endif %}
    <div class="social-icons">
      <a href="https://t.me/pestina_co"  rel="nofollow" target="_blank" aria-label="تلگرام"><i class="fab fa-telegram"></i>&nbsp;تلگرام</a>
      <a href="https://www.intagram.com/pestina_co" rel="nofollow" target="_blank"  aria-label="اینستاگرام"><i class="fab fa-instagram"></i>&nbsp;اینستاگرام</a>
      <a href="https://x.com/pestina_co"  rel="nofollow" target="_blank" aria-label="توییتر"><i class="fab fa-twitter"></i>&nbsp;شبکه ایکس</a>
      <a href="{% url 'send-ticket' 'technical' %}"><i class="fa-duotone fa-solid fa-phone"></i>&nbsp;پشتیبانی</a>
    </div>
    <div class="buttons">
      <a href="{% url 'home' %}"><i class="fa-duotone fa-solid fa-home"></i>&nbsp;خانه</a>
      <a href="javascript:history.back()"><i class="fa-duotone fa-solid fa-backward"></i>&nbsp;بازگشت</a>
    </div>
  </div>
</body>
</html>